<a href="https://colab.research.google.com/github/shreeyashbaran/Info-5731/blob/main/Baranwal_Shreeyash_Assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INFO5731 Assignment 1**

In this assignment, you will work on gathering text data from an open data source via web scraping or API. Following this, you will need to clean the text data and perform syntactic analysis on the data. Follow the instructions carefully and design well-structured Python programs to address each question.

**Expectations**:
*   Use the provided .*ipynb* document to write your code & respond to the questions. Avoid generating a new file.
*   Write complete answers and run all the cells before submission.
*   Make sure the submission is "clean"; *i.e.*, no unnecessary code cells.
*   Once finished, allow shared rights from top right corner (*see Canvas for details*).

* **Make sure to submit the cleaned data CSV in the comment section - 10 points**

**Total points**: 100


**Late Submission will have a penalty of 10% reduction for each day after the deadline.**

**Please check that the link you submitted can be opened and points to the correct assignment.**

# Question 1 (25 points)

Write a python program to collect text data from **either of the following sources** and save the data into a **csv file:**

(1) Collect all the customer reviews of a product (you can choose any porduct) on amazon. [atleast 1000 reviews]

(2) Collect the top 1000 User Reviews of a movie recently in 2024 or 2025 (you can choose any movie) from IMDB. [If one movie doesn't have sufficient reviews, collect reviews of atleast 2 or 3 movies]


(3) Collect the **abstracts** of the top 10000 research papers by using the query "machine learning", "data science", "artifical intelligence", or "information extraction" from Semantic Scholar.

(4) Collect all the information of the 904 narrators in the Densho Digital Repository.

(5)**Collect a total of 10000 reviews** of the top 100 most popular software from G2 and Capterra.

In [32]:
import os
import re
import time
import random
import requests
import pandas as pd

In [33]:
# =========================
QUERY = "data science"   # or: "machine learning", "data science", "artificial intelligence"
TARGET_N = 10_000

# Optional filters (leave as None to maximize results)
YEAR_RANGE = None          # examples: "2020-" or "2018-2025" or "2024-2025"
MIN_CITATIONS = None       # example: 10

# Sorting: bulk search supports sorting (helps justify "top" papers)
SORT = "citationCount:desc"  # if API rejects this, code will auto-fallback

# Keep fields small (faster + less likely to hit response size limits)
FIELDS = "paperId,title,abstract,year,citationCount,url"

# Optional: API key (recommended).
# You can request one from your Semantic Scholar account settings.
S2_API_KEY = os.getenv("S2_API_KEY", "")  # set in Colab: os.environ["S2_API_KEY"]="..."

In [34]:
BASE_URL = "https://api.semanticscholar.org/graph/v1/paper/search/bulk"

def _clean_params(d):
    return {k: v for k, v in d.items() if v not in (None, "", [])}

def fetch_semantic_scholar_abstracts(
    query: str,
    target_n: int = 10_000,
    fields: str = "paperId,title,abstract,year,citationCount,url",
    year_range: str | None = None,
    min_citations: int | None = None,
    sort: str | None = "citationCount:desc",
    api_key: str = "",
    polite_sleep: tuple[float, float] = (0.9, 1.3),
):
    headers = {"User-Agent": "UNT-DTSC-webscrape-assignment/1.0"}
    if api_key:
        headers["x-api-key"] = api_key

    token = None
    rows = []
    seen_ids = set()

    # We'll try with sort first; if API errors, we retry without sort.
    use_sort = True if sort else False

    while len(rows) < target_n:
        params = {
            "query": query,
            "fields": fields,
            "token": token,
            "year": year_range,
            "minCitationCount": min_citations,
            "sort": sort if use_sort else None,
        }
        params = _clean_params(params)

        resp = requests.get(BASE_URL, params=params, headers=headers, timeout=60)

        # Handle rate limiting politely
        if resp.status_code == 429:
            wait = random.uniform(3.0, 6.0)
            print(f"[429] Rate limited. Sleeping {wait:.1f}s then retrying...")
            time.sleep(wait)
            continue

        # If sort causes a 400/422, retry once without sort
        if resp.status_code in (400, 422) and use_sort:
            print("[INFO] Sort parameter rejected by API for this request. Retrying without sort...")
            use_sort = False
            continue

        resp.raise_for_status()
        data = resp.json()

        if "total" in data and token is None:
            print(f"Estimated total matches: {data['total']}")

        batch = data.get("data", [])
        if not batch:
            print("[INFO] No more results returned.")
            break

        for p in batch:
            pid = p.get("paperId")
            if not pid or pid in seen_ids:
                continue
            seen_ids.add(pid)
            rows.append(p)
            if len(rows) >= target_n:
                break

        token = data.get("token", None)
        print(f"Collected {len(rows):,}/{target_n:,} | token={'YES' if token else 'NO'}")

        if not token:
            break

        # Polite pacing (works even without API key)
        time.sleep(random.uniform(*polite_sleep))

    return rows

In [35]:
papers = fetch_semantic_scholar_abstracts(
    query=QUERY,
    target_n=TARGET_N,
    fields=FIELDS,
    year_range=YEAR_RANGE,
    min_citations=MIN_CITATIONS,
    sort=SORT,
    api_key=S2_API_KEY,
)

df_raw = pd.DataFrame(papers)

raw_path = "semantic_scholar_raw.csv"
df_raw.to_csv(raw_path, index=False)
print("Saved:", raw_path)
df_raw.head(3)

Estimated total matches: 797242
Collected 999/10,000 | token=YES
Collected 1,999/10,000 | token=YES
Collected 2,999/10,000 | token=YES
Collected 3,999/10,000 | token=YES
Collected 4,999/10,000 | token=YES
Collected 5,999/10,000 | token=YES
Collected 6,999/10,000 | token=YES
Collected 7,999/10,000 | token=YES
Collected 8,999/10,000 | token=YES
Collected 9,998/10,000 | token=YES
Collected 10,000/10,000 | token=YES
Saved: semantic_scholar_raw.csv

,paperId,url,title,year,citationCount,openAccessPdf,authors,abstract
0,39179d84ebd2670e6092ca8a296ce3b72a1ea3ed,https://www.semanticscholar.org/paper/39179d84...,Case Study Research: Design and Methods,1984.0,52471,"{'url': '', 'status': None, 'license': None}","[{'authorId': '52533369', 'name': 'R. Yin'}]",None
1,f12ea2b37862738605236add280919c762aeebcd,https://www.semanticscholar.org/paper/f12ea2b3...,Principles and Practice of Structural Equation...,1998.0,50178,"{'url': '', 'status': None, 'license': None}","[{'authorId': '18213872', 'name': 'R. Kline'}]",None
2,cae155b295abd5b0ab02fb26351720c40e969907,https://www.semanticscholar.org/paper/cae155b2...,The Structure of Scientific Revolutions,1963.0,47828,"{'url': '', 'status': 'CLOSED', 'license': Non...","[{'authorId': '46341118', 'name': 'T. Kuhn'}, ...",None

# Question 2 (15 points)

Write a python program to **clean the text data** you collected in the previous question and save the clean data in a new column in the csv file. The data cleaning steps include: [Code and output is required for each part]

(1) Remove noise, such as special characters and punctuations.

(2) Remove numbers.

(3) Remove stopwords by using the stopwords list.

(4) Lowercase all texts

(5) Stemming.

(6) Lemmatization.

In [51]:
import pandas as pd

RAW_FILE = "semantic_scholar_raw.csv"

TEXT_COL = "abstract"  # This is the text column we will clean

df = pd.read_csv(RAW_FILE)
df[TEXT_COL] = df[TEXT_COL].fillna("").astype(str)

print("Loaded file:", RAW_FILE)
print("Rows:", len(df))
print("Text column:", TEXT_COL)

df[[TEXT_COL]].head(3)

Loaded file: semantic_scholar_raw.csv
Rows: 10000
Text column: abstract

  abstract
0
1
2

In [52]:
# Check how many abstracts are missing (this is normal for Semantic Scholar)
empty_mask = df[TEXT_COL].str.strip().eq("")

print("Total rows:", len(df))
print("Empty abstracts:", int(empty_mask.sum()))
print("Empty abstract rate:", round(float(empty_mask.mean()), 4))

# Work only on rows that actually have text (so your before/after outputs are meaningful)
df_work = df.loc[~empty_mask].copy()

print("\nOriginal rows:", len(df))
print("Usable rows with abstract:", len(df_work))
print("Dropped rows (missing abstract):", len(df) - len(df_work))

# Pick 3 stable samples for before/after printing
sample_idx = df_work.sample(3, random_state=42).index.tolist()
print("\nSample row indexes for step outputs:", sample_idx)

df_work[[TEXT_COL]].head(3)

Total rows: 10000
Empty abstracts: 6878
Empty abstract rate: 0.6878

Original rows: 10000
Usable rows with abstract: 3122
Dropped rows (missing abstract): 6878

Sample row indexes for step outputs: [9633, 9541, 6890]

                                             abstract
9   Background Since December, 2019, Wuhan, China,...
12  diabetes statistics cdc ��glucagon megaroll.in...
13  Array programming provides a powerful, compact...

In [53]:
import re

def normalize_spaces(s: str) -> str:
    return re.sub(r"\s+", " ", s).strip()

def step1_remove_noise(text: str) -> str:
    # Keep letters, numbers, and spaces; replace everything else with space
    text = re.sub(r"[^A-Za-z0-9\s]", " ", text)
    return normalize_spaces(text)

df_work["step1_no_punct"] = df_work[TEXT_COL].apply(step1_remove_noise)

print("=== Step 1: Remove noise (punctuation/special chars) ===")
for j, i in enumerate(sample_idx, start=1):
    print(f"\n--- Example {j} ---")
    print("BEFORE:", df_work.loc[i, TEXT_COL][:250])
    print("AFTER: ", df_work.loc[i, "step1_no_punct"][:250])

df_work[[TEXT_COL, "step1_no_punct"]].head(3)

=== Step 1: Remove noise (punctuation/special chars) ===

--- Example 1 ---
BEFORE: The role of MRI in diagnostics, prognostics, and discoveries in basic sciences has been well established. However, access to this life‐saving technology is largely restricted to countries in upper‐middle to high‐income groups. In this article, we col
AFTER:  The role of MRI in diagnostics prognostics and discoveries in basic sciences has been well established However access to this life saving technology is largely restricted to countries in upper middle to high income groups In this article we collate r

--- Example 2 ---
BEFORE: With the routine use of electronic health records (EHRs) in hospitals, health systems, and physician practices, there has been rapid growth in the availability of health care data over the last decade. In addition to the structured data in EHRs, new
AFTER:  With the routine use of electronic health records EHRs in hospitals health systems and physician practices there has been rapid growth in the availability of health care data over the last decade In addition to the structured data in EHRs new methods

--- Example 3 ---
BEFORE: Poisson regression is a popular tool for modeling count data and is applied in a vast array of applications from the social to the physical sciences and beyond. Real data, however, are often over- or under-dispersed and, thus, not conducive to Poisso
AFTER:  Poisson regression is a popular tool for modeling count data and is applied in a vast array of applications from the social to the physical sciences and beyond Real data however are often over or under dispersed and thus not conducive to Poisson regr

,abstract,step1_no_punct
9,"Background Since December, 2019, Wuhan, China,...",Background Since December 2019 Wuhan China has...
12,diabetes statistics cdc ��glucagon megaroll.in...,diabetes statistics cdc glucagon megaroll info...
13,"Array programming provides a powerful, compact...",Array programming provides a powerful compact ...

In [54]:
def step2_remove_numbers(text: str) -> str:
    # Remove digits (0-9)
    text = re.sub(r"\d+", " ", text)
    return normalize_spaces(text)

df_work["step2_no_numbers"] = df_work["step1_no_punct"].apply(step2_remove_numbers)

print("=== Step 2: Remove numbers ===")
for j, i in enumerate(sample_idx, start=1):
    print(f"\n--- Example {j} ---")
    print("BEFORE:", df_work.loc[i, "step1_no_punct"][:250])
    print("AFTER: ", df_work.loc[i, "step2_no_numbers"][:250])

df_work[["step1_no_punct", "step2_no_numbers"]].head(3)

=== Step 2: Remove numbers ===

--- Example 1 ---
BEFORE: The role of MRI in diagnostics prognostics and discoveries in basic sciences has been well established However access to this life saving technology is largely restricted to countries in upper middle to high income groups In this article we collate r
AFTER:  The role of MRI in diagnostics prognostics and discoveries in basic sciences has been well established However access to this life saving technology is largely restricted to countries in upper middle to high income groups In this article we collate r

--- Example 2 ---
BEFORE: With the routine use of electronic health records EHRs in hospitals health systems and physician practices there has been rapid growth in the availability of health care data over the last decade In addition to the structured data in EHRs new methods
AFTER:  With the routine use of electronic health records EHRs in hospitals health systems and physician practices there has been rapid growth in the availability of health care data over the last decade In addition to the structured data in EHRs new methods

--- Example 3 ---
BEFORE: Poisson regression is a popular tool for modeling count data and is applied in a vast array of applications from the social to the physical sciences and beyond Real data however are often over or under dispersed and thus not conducive to Poisson regr
AFTER:  Poisson regression is a popular tool for modeling count data and is applied in a vast array of applications from the social to the physical sciences and beyond Real data however are often over or under dispersed and thus not conducive to Poisson regr

,step1_no_punct,step2_no_numbers
9,Background Since December 2019 Wuhan China has...,Background Since December Wuhan China has expe...
12,diabetes statistics cdc glucagon megaroll info...,diabetes statistics cdc glucagon megaroll info...
13,Array programming provides a powerful compact ...,Array programming provides a powerful compact ...

In [55]:
df_work["step4_lower"] = df_work["step2_no_numbers"].str.lower()

print("=== Step 4: Lowercase ===")
for j, i in enumerate(sample_idx, start=1):
    print(f"\n--- Example {j} ---")
    print("BEFORE:", df_work.loc[i, "step2_no_numbers"][:250])
    print("AFTER: ", df_work.loc[i, "step4_lower"][:250])

df_work[["step2_no_numbers", "step4_lower"]].head(3)

=== Step 4: Lowercase ===

--- Example 1 ---
BEFORE: The role of MRI in diagnostics prognostics and discoveries in basic sciences has been well established However access to this life saving technology is largely restricted to countries in upper middle to high income groups In this article we collate r
AFTER:  the role of mri in diagnostics prognostics and discoveries in basic sciences has been well established however access to this life saving technology is largely restricted to countries in upper middle to high income groups in this article we collate r

--- Example 2 ---
BEFORE: With the routine use of electronic health records EHRs in hospitals health systems and physician practices there has been rapid growth in the availability of health care data over the last decade In addition to the structured data in EHRs new methods
AFTER:  with the routine use of electronic health records ehrs in hospitals health systems and physician practices there has been rapid growth in the availability of health care data over the last decade in addition to the structured data in ehrs new methods

--- Example 3 ---
BEFORE: Poisson regression is a popular tool for modeling count data and is applied in a vast array of applications from the social to the physical sciences and beyond Real data however are often over or under dispersed and thus not conducive to Poisson regr
AFTER:  poisson regression is a popular tool for modeling count data and is applied in a vast array of applications from the social to the physical sciences and beyond real data however are often over or under dispersed and thus not conducive to poisson regr

,step2_no_numbers,step4_lower
9,Background Since December Wuhan China has expe...,background since december wuhan china has expe...
12,diabetes statistics cdc glucagon megaroll info...,diabetes statistics cdc glucagon megaroll info...
13,Array programming provides a powerful compact ...,array programming provides a powerful compact ...

In [56]:
df_work["step4_lower"] = df_work["step2_no_numbers"].str.lower()

print("=== Step 4: Lowercase ===")
for j, i in enumerate(sample_idx, start=1):
    print(f"\n--- Example {j} ---")
    print("BEFORE:", df_work.loc[i, "step2_no_numbers"][:250])
    print("AFTER: ", df_work.loc[i, "step4_lower"][:250])

df_work[["step2_no_numbers", "step4_lower"]].head(3)

=== Step 4: Lowercase ===

--- Example 1 ---
BEFORE: The role of MRI in diagnostics prognostics and discoveries in basic sciences has been well established However access to this life saving technology is largely restricted to countries in upper middle to high income groups In this article we collate r
AFTER:  the role of mri in diagnostics prognostics and discoveries in basic sciences has been well established however access to this life saving technology is largely restricted to countries in upper middle to high income groups in this article we collate r

--- Example 2 ---
BEFORE: With the routine use of electronic health records EHRs in hospitals health systems and physician practices there has been rapid growth in the availability of health care data over the last decade In addition to the structured data in EHRs new methods
AFTER:  with the routine use of electronic health records ehrs in hospitals health systems and physician practices there has been rapid growth in the availability of health care data over the last decade in addition to the structured data in ehrs new methods

--- Example 3 ---
BEFORE: Poisson regression is a popular tool for modeling count data and is applied in a vast array of applications from the social to the physical sciences and beyond Real data however are often over or under dispersed and thus not conducive to Poisson regr
AFTER:  poisson regression is a popular tool for modeling count data and is applied in a vast array of applications from the social to the physical sciences and beyond real data however are often over or under dispersed and thus not conducive to poisson regr

,step2_no_numbers,step4_lower
9,Background Since December Wuhan China has expe...,background since december wuhan china has expe...
12,diabetes statistics cdc glucagon megaroll info...,diabetes statistics cdc glucagon megaroll info...
13,Array programming provides a powerful compact ...,array programming provides a powerful compact ...

In [57]:
import nltk
nltk.download("stopwords")

from nltk.corpus import stopwords
stop_words = set(stopwords.words("english"))

def step3_remove_stopwords(text: str) -> str:
    tokens = text.split()
    kept = [t for t in tokens if t not in stop_words]
    return " ".join(kept)

df_work["step3_no_stopwords"] = df_work["step4_lower"].apply(step3_remove_stopwords)

print("=== Step 3: Remove stopwords ===")
for j, i in enumerate(sample_idx, start=1):
    print(f"\n--- Example {j} ---")
    print("BEFORE:", df_work.loc[i, "step4_lower"][:250])
    print("AFTER: ", df_work.loc[i, "step3_no_stopwords"][:250])

df_work[["step4_lower", "step3_no_stopwords"]].head(3)

=== Step 3: Remove stopwords ===

--- Example 1 ---
BEFORE: the role of mri in diagnostics prognostics and discoveries in basic sciences has been well established however access to this life saving technology is largely restricted to countries in upper middle to high income groups in this article we collate r
AFTER:  role mri diagnostics prognostics discoveries basic sciences well established however access life saving technology largely restricted countries upper middle high income groups article collate recent global mr scanner density data group six geographic

--- Example 2 ---
BEFORE: with the routine use of electronic health records ehrs in hospitals health systems and physician practices there has been rapid growth in the availability of health care data over the last decade in addition to the structured data in ehrs new methods
AFTER:  routine use electronic health records ehrs hospitals health systems physician practices rapid growth availability health care data last decade addition structured data ehrs new methods natural language processing derive meaning unstructured data perm

--- Example 3 ---
BEFORE: poisson regression is a popular tool for modeling count data and is applied in a vast array of applications from the social to the physical sciences and beyond real data however are often over or under dispersed and thus not conducive to poisson regr
AFTER:  poisson regression popular tool modeling count data applied vast array applications social physical sciences beyond real data however often dispersed thus conducive poisson regression propose regression model based conway maxwell poisson cmp distribu

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,step4_lower,step3_no_stopwords
9,background since december wuhan china has expe...,background since december wuhan china experien...
12,diabetes statistics cdc glucagon megaroll info...,diabetes statistics cdc glucagon megaroll info...
13,array programming provides a powerful compact ...,array programming provides powerful compact ex...

In [58]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

def step5_stem(text: str) -> str:
    tokens = text.split()
    stemmed = [stemmer.stem(t) for t in tokens]
    return " ".join(stemmed)

df_work["step5_stem"] = df_work["step3_no_stopwords"].apply(step5_stem)

print("=== Step 5: Stemming ===")
for j, i in enumerate(sample_idx, start=1):
    print(f"\n--- Example {j} ---")
    print("BEFORE:", df_work.loc[i, "step3_no_stopwords"][:250])
    print("AFTER: ", df_work.loc[i, "step5_stem"][:250])

df_work[["step3_no_stopwords", "step5_stem"]].head(3)

=== Step 5: Stemming ===

--- Example 1 ---
BEFORE: role mri diagnostics prognostics discoveries basic sciences well established however access life saving technology largely restricted countries upper middle high income groups article collate recent global mr scanner density data group six geographic
AFTER:  role mri diagnost prognost discoveri basic scienc well establish howev access life save technolog larg restrict countri upper middl high incom group articl collat recent global mr scanner densiti data group six geograph region base classif analyz dat

--- Example 2 ---
BEFORE: routine use electronic health records ehrs hospitals health systems physician practices rapid growth availability health care data last decade addition structured data ehrs new methods natural language processing derive meaning unstructured data perm
AFTER:  routin use electron health record ehr hospit health system physician practic rapid growth avail health care data last decad addit structur data ehr new method natur languag process deriv mean unstructur data permit captur substanti clinic inform embe

--- Example 3 ---
BEFORE: poisson regression popular tool modeling count data applied vast array applications social physical sciences beyond real data however often dispersed thus conducive poisson regression propose regression model based conway maxwell poisson cmp distribu
AFTER:  poisson regress popular tool model count data appli vast array applic social physic scienc beyond real data howev often dispers thu conduc poisson regress propos regress model base conway maxwel poisson cmp distribut address problem cmp regress gener

,step3_no_stopwords,step5_stem
9,background since december wuhan china experien...,background sinc decemb wuhan china experienc o...
12,diabetes statistics cdc glucagon megaroll info...,diabet statist cdc glucagon megarol infocorn o...
13,array programming provides powerful compact ex...,array program provid power compact express syn...

In [59]:
nltk.download("wordnet")
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

def step6_lemmatize(text: str) -> str:
    tokens = text.split()
    lemmas = []
    for t in tokens:
        # Simple approach: noun → verb (covers many cases reasonably)
        w = lemmatizer.lemmatize(t)
        w = lemmatizer.lemmatize(w, pos="v")
        lemmas.append(w)
    return " ".join(lemmas)

df_work["step6_lemma"] = df_work["step3_no_stopwords"].apply(step6_lemmatize)

print("=== Step 6: Lemmatization ===")
for j, i in enumerate(sample_idx, start=1):
    print(f"\n--- Example {j} ---")
    print("BEFORE:", df_work.loc[i, "step3_no_stopwords"][:250])
    print("AFTER: ", df_work.loc[i, "step6_lemma"][:250])

df_work[["step3_no_stopwords", "step6_lemma"]].head(3)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

=== Step 6: Lemmatization ===

--- Example 1 ---
BEFORE: role mri diagnostics prognostics discoveries basic sciences well established however access life saving technology largely restricted countries upper middle high income groups article collate recent global mr scanner density data group six geographic
AFTER:  role mri diagnostics prognostic discovery basic science well establish however access life save technology largely restrict country upper middle high income group article collate recent global mr scanner density data group six geographical region bas

--- Example 2 ---
BEFORE: routine use electronic health records ehrs hospitals health systems physician practices rapid growth availability health care data last decade addition structured data ehrs new methods natural language processing derive meaning unstructured data perm
AFTER:  routine use electronic health record ehrs hospital health system physician practice rapid growth availability health care data last decade addition structure data ehrs new method natural language process derive mean unstructured data permit capture s

--- Example 3 ---
BEFORE: poisson regression popular tool modeling count data applied vast array applications social physical sciences beyond real data however often dispersed thus conducive poisson regression propose regression model based conway maxwell poisson cmp distribu
AFTER:  poisson regression popular tool model count data apply vast array application social physical science beyond real data however often disperse thus conducive poisson regression propose regression model base conway maxwell poisson cmp distribution addr

,step3_no_stopwords,step6_lemma
9,background since december wuhan china experien...,background since december wuhan china experien...
12,diabetes statistics cdc glucagon megaroll info...,diabetes statistic cdc glucagon megaroll infoc...
13,array programming provides powerful compact ex...,array program provide powerful compact express...

In [60]:
# Final clean column (this is the one you'll use in Q3)
df_work["clean_text_final"] = df_work["step6_lemma"]

# Build output dataframe (keep full 10,000 rows; fill cleaned columns only where abstracts existed)
df_out = df.copy()

step_cols = [
    "step1_no_punct",
    "step2_no_numbers",
    "step4_lower",
    "step3_no_stopwords",
    "step5_stem",
    "step6_lemma",
    "clean_text_final"
]

# Initialize columns so the CSV is consistent
for c in step_cols:
    df_out[c] = ""

# Write results back for the rows we processed
for c in step_cols:
    df_out.loc[df_work.index, c] = df_work[c].astype(str)

# Save outputs
OUT_FILE = "semantic_scholar_cleaned_with_steps.csv"
WORK_FILE = "semantic_scholar_working_abstracts_only.csv"

df_out.to_csv(OUT_FILE, index=False)
df_work.to_csv(WORK_FILE, index=False)

print("Saved full file (10,000 rows):", OUT_FILE)
print("Saved working file (non-empty abstracts only):", WORK_FILE)

# quick preview
df_out[[TEXT_COL, "clean_text_final"]].head(5)

Saved full file (10,000 rows): semantic_scholar_cleaned_with_steps.csv
Saved working file (non-empty abstracts only): semantic_scholar_working_abstracts_only.csv

  abstract clean_text_final
0
1
2
3
4

# Question 3 (15 points)

Write a python program to **conduct syntax and structure analysis of the clean text** you just saved above. The syntax and structure analysis includes:

(1) **Parts of Speech (POS) Tagging:** Tag Parts of Speech of each word in the text, and calculate the total number of N(oun), V(erb), Adj(ective), Adv(erb), respectively.

(2) **Constituency Parsing and Dependency Parsing:** print out the constituency parsing trees and dependency parsing trees of all the sentences. Using one sentence as an example to explain your understanding about the constituency parsing tree and dependency parsing tree.

(3) **Named Entity Recognition:** Extract all the entities such as person names, organizations, locations, product names, and date from the clean texts, calculate the count of each entity.

In [44]:
!pip -q install spacy benepar
!python -m spacy download en_core_web_sm -q

  Preparing metadata (setup.py) ... done
  Building wheel for benepar (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 65.1 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [45]:
import benepar
benepar.download("benepar_en3")
!pip -q install spacy stanza
!python -m spacy download en_core_web_sm -q

[nltk_data] Downloading package benepar_en3 to /root/nltk_data...
[nltk_data]   Unzipping models/benepar_en3.zip.

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 20.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 773.7/773.7 kB 29.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 25.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 337.2/337.2 kB 13.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 87.5 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [46]:
import stanza
stanza.download("en")

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json:   0%|  …

INFO:stanza:Downloaded file to /root/.cache/stanza/1.11.0/resources/resources.json
INFO:stanza:Downloading default packages for language: en (English) ...

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.11.0/models/default.zip:   0%|          | …

INFO:stanza:Downloaded file to /root/.cache/stanza/1.11.0/resources/en/default.zip
INFO:stanza:Finished downloading models and saved to /root/.cache/stanza/1.11.0/resources

[['zip', 'default.zip']]

In [61]:
import pandas as pd

df = pd.read_csv("semantic_scholar_cleaned_with_steps.csv")  # change if needed
CLEAN_COL = "clean_text_final"  # change if your column name differs

df[CLEAN_COL] = df[CLEAN_COL].fillna("").astype(str)

print("Rows:", len(df))
df[[CLEAN_COL]].head(3)

Rows: 10000

  clean_text_final
0
1
2

In [62]:
import spacy
from collections import Counter

# Keep only what's needed for speed
nlp_pos = spacy.load("en_core_web_sm", disable=["parser", "lemmatizer", "ner"])

def pos_bucket(token):
    # Count PROPN as NOUN; AUX as VERB (common grading expectation)
    if token.pos_ in ("NOUN", "PROPN"):
        return "NOUN"
    if token.pos_ in ("VERB", "AUX"):
        return "VERB"
    if token.pos_ == "ADJ":
        return "ADJ"
    if token.pos_ == "ADV":
        return "ADV"
    return None

pos_counts = Counter({"NOUN": 0, "VERB": 0, "ADJ": 0, "ADV": 0})

texts = df[CLEAN_COL].tolist()

for doc in nlp_pos.pipe(texts, batch_size=64):
    for t in doc:
        b = pos_bucket(t)
        if b:
            pos_counts[b] += 1

print("POS TOTAL COUNTS (entire dataset):")
print(pos_counts)

POS TOTAL COUNTS (entire dataset):
Counter({'NOUN': 379783, 'ADJ': 108707, 'VERB': 74282, 'ADV': 20845})

In [63]:
import stanza

stz = stanza.Pipeline(
    "en",
    processors="tokenize,pos,lemma,depparse,constituency",
    tokenize_no_ssplit=False,
    use_gpu=False
)

DOCS_TO_PARSE = 2            # increase if you want more texts
MAX_SENTENCES_PER_DOC = 6    # increase if you want more sentences printed

def dependency_lines_stanza(sent):
    # sent.words: each has id (1..n), head (0..n), deprel
    id2text = {w.id: w.text for w in sent.words}
    lines = []
    for w in sent.words:
        head_txt = "ROOT" if w.head == 0 else id2text.get(w.head, "UNK")
        lines.append(f"{w.text:<15} -> {head_txt:<15} ({w.deprel})")
    return "\n".join(lines)

printed_docs = 0
example_sentence_text = None
example_const_tree = None
example_dep_lines = None

# pick first non-empty docs
for text in df[CLEAN_COL]:
    if not text or len(text.strip()) < 40:
        continue

    doc = stz(text)
    if len(doc.sentences) == 0:
        continue

    print("\n" + "#"*100)
    print(f"DOCUMENT {printed_docs+1}")
    print("#"*100)

    s_count = 0
    for sent in doc.sentences:
        sent_text = sent.text.strip()
        if len(sent_text) < 25:
            continue

        s_count += 1
        print("\n" + "="*90)
        print(f"Sentence {s_count}: {sent_text}\n")

        # Constituency tree (bracket format)
        print("Constituency Parse Tree:")
        print(str(sent.constituency))

        # Dependency “tree” as token -> head (relation)
        print("\nDependency Parse (token -> head (relation)):")
        dep = dependency_lines_stanza(sent)
        print(dep)

        # Save first sentence as your “one sentence example”
        if example_sentence_text is None:
            example_sentence_text = sent_text
            example_const_tree = str(sent.constituency)
            example_dep_lines = dep

        if s_count >= MAX_SENTENCES_PER_DOC:
            break

    printed_docs += 1
    if printed_docs >= DOCS_TO_PARSE:
        break

print("\n" + "#"*100)
print("ONE SENTENCE TO USE FOR YOUR EXPLANATION:")
print(example_sentence_text)

INFO:stanza:Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json:   0%|  …

INFO:stanza:Downloaded file to /root/.cache/stanza/1.11.0/resources/resources.json
WARNING:stanza:Language en package default expects mwt, which has been added
INFO:stanza:Loading these models for language: en (English):
======================================
| Processor    | Package             |
--------------------------------------
| tokenize     | combined            |
| mwt          | combined            |
| pos          | combined_charlm     |
| lemma        | combined_nocharlm   |
| constituency | ptb3-revised_charlm |
| depparse     | combined_charlm     |
======================================

INFO:stanza:Using device: cpu
INFO:stanza:Loading: tokenize
INFO:stanza:Loading: mwt
INFO:stanza:Loading: pos
INFO:stanza:Loading: lemma
INFO:stanza:Loading: constituency
INFO:stanza:Loading: depparse
INFO:stanza:Done loading processors!

####################################################################################################
DOCUMENT 1
####################################################################################################

==========================================================================================
Sentence 1: background since december wuhan china experience outbreak coronavirus disease covid cause severe acute respiratory syndrome coronavirus sars cov epidemiological clinical characteristic patient covid report risk factor mortality detail clinical course illness include viral shed well describe method retrospective multicentre cohort study include adult inpatient year old laboratory confirm covid jinyintan hospital wuhan pulmonary hospital wuhan china discharge die jan demographic clinical treatment laboratory data include serial sample viral rna detection extract electronic medical record compare survivor non survivor use univariable multivariable logistic regression method explore risk factor associate hospital death find patient jinyintan hospital wuhan pulmonary hospital include study discharge die hospital patient comorbidity hypertension common patient follow diabetes patient coronary heart disease patient multivariable regression show increase odds hospital death associate older age odds ratio ci per year increase p higher sequential organ failure assessment sofa score p dimer greater g ml p admission median duration viral shed day iqr survivor sars cov detectable death non survivor longest observe duration viral shed survivor day interpretation potential risk factor older age high sofa score dimer greater g ml could help clinician identify patient poor prognosis early stage prolong viral shed provide rationale strategy isolation infect patient optimal antiviral intervention future fund chinese academy medical science innovation fund medical science national science grant distinguish young scholar national key research development program china beijing science technology project major project national science technology new drug creation development

Constituency Parse Tree:
(ROOT (S (NP (NP (NN background)) (PP (IN since) (NP (NML (NNP december) (NNP wuhan)) (NML (NML (NML (NN china) (NN experience)) (NN outbreak)) (NN coronavirus) (NN disease)) (NN covid)))) (VP (VBP cause) (SBAR (S (S (NML (NML (JJ severe) (JJ acute)) (NML (JJ respiratory) (NN syndrome)) (NN coronavirus) (NNS sars)) (VP (NN cov) (NP (NML (NML (NML (JJ epidemiological) (JJ clinical) (JJ characteristic)) (NN patient) (NN covid) (NN report)) (NML (NN risk) (NN factor)) (NN mortality) (NN detail)) (NML (JJ clinical) (NN course)) (NN illness)))) (VP (VBP include) (S (NP (JJ viral) (NN shed) (RB well)) (VP (VB describe) (SBAR (S (NP (NML (NN method) (NN retrospective)) (NN multicentre) (NN cohort) (NN study)) (VP (VBP include) (SBAR (S (NP (NML (NP (NN adult) (JJ inpatient) (NN year) (JJ old) (NN laboratory)) (NN confirm) (NML (NML (NN covid) (NN jinyintan)) (NN hospital) (NN wuhan)) (NML (JJ pulmonary) (NN hospital)) (NN wuhan) (NN china)) (NN discharge)) (VP (VBP die) (SBAR (S (NP (NML (NML (NN jan) (NN demographic)) (NML (JJ clinical) (NN treatment)) (NN laboratory)) (NNS data)) (VP (VBP include) (S (NP (NML (JJ serial) (NN sample)) (NML (NML (NML (NML (NML (JJ viral) (NN rna)) (NN detection)) (NN extract)) (JJ electronic) (JJ medical) (NN record)) (NN compare)) (NP (NN survivor)) (NN non) (NN survivor) (NN use) (JJ univariable) (JJ multivariable) (JJ logistic) (NN regression) (NN method)) (VP (VB explore) (S (NP (NML (NN risk) (NN factor)) (NN associate) (NN hospital) (NN death)) (VP (VB find) (SBAR (S (NP (NML (NML (NN patient) (NN jinyintan)) (NN hospital) (NN wuhan)) (JJ pulmonary) (NN hospital)) (VP (VBP include) (SBAR (S (NP (NN study) (NN discharge)) (VP (VBP die) (SBAR (S (NP (NML (NN hospital) (NN patient) (NN comorbidity) (NN hypertension)) (JJ common) (NN patient)) (VP (NN follow) (NP (NML (NML (NML (NML (NN diabetes) (NN patient)) (NN coronary) (NN heart) (NN disease)) (NN patient)) (JJ multivariable) (NN regression)) (NN show)) (S (VP (NN increase) (NP (NML (NNS odds) (NML (NML (NN hospital) (NN death)) (NN associate))) (NML (NML (NML (NML (NML (NML (JJR older) (NN age)) (NNS odds)) (NN ratio)) (NN ci) (PP (IN per) (NP (NN year)))) (NN increase)) (PP (NN p) (NP (JJR higher) (JJ sequential) (NML (NML (NML (NN organ) (NN failure)) (NN assessment)) (NML (NN sofa) (NN score)) (NN p) (NN dimer) (JJR greater) (NN g) (NN ml) (NN p) (NN admission) (NN median) (NN duration) (NML (NN viral) (NN shed)) (NN day)) (NML (NML (NML (NNP iqr) (NN survivor)) (NNS sars)) (NN cov)) (NML (NML (JJ detectable) (NN death)) (NN non) (NN survivor)) (NML (NML (JJS longest) (NN observe) (NN duration)) (NML (NML (NML (JJ viral) (NN shed)) (NN survivor) (NN day) (NN interpretation)) (SBAR (S (NML (NML (NN potential) (NN risk) (NN factor)) (NML (JJR older) (NN age)) (JJ high) (NML (NN sofa) (NN score)) (NN dimer) (NML (JJR greater) (NN g)) (NNS ml)) (VP (MD could) (VP (VB help) (S (NP (NN clinician)) (VP (VB identify) (NP (JJ patient) (JJ poor) (NN prognosis)) (S (NP (JJ early) (NN stage)) (VP (VB prolong) (S (NP (JJ viral) (NN shed)) (VP (VB provide) (NP (NP (NN rationale) (NN strategy) (NN isolation)) (VP (VB infect) (S (NP (NML (NN patient) (JJ optimal)) (NML (NML (JJ antiviral) (NN intervention)) (JJ future) (NN fund)) (NML (NML (JJ chinese) (NN academy)) (NML (NML (NML (JJ medical) (NN science)) (NN innovation)) (NN fund))) (NML (JJ medical) (NN science)) (JJ national) (NN science) (NN grant)) (VP (VB distinguish) (NP (JJ young) (NN scholar) (JJ national) (NML (NML (NML (JJ key) (NN research) (NN development)) (NN program)) (NN china)) (NML (NML (NN beijing) (NN science) (NN technology)) (NN project)) (NML (JJ major) (NN project)) (NML (JJ national) (NN science) (NN technology)) (NML (JJ new) (NN drug) (NN creation)) (NN development))))))))))))))))))))))))))))))))))))))))))))))))))))))

Dependency Parse (token -> head (relation)):
background      -> include         (nsubj)
since           -> december        (case)
december        -> background      (nmod)
wuhan           -> december        (flat)
china           -> experience      (compound)
experience      -> outbreak        (compound)
outbreak        -> covid           (compound)
coronavirus     -> covid           (compound)
disease         -> covid           (compound)
covid           -> cause           (nsubj)
cause           -> include         (advcl)
severe          -> sars            (amod)
acute           -> sars            (amod)
respiratory     -> syndrome        (amod)
syndrome        -> sars            (compound)
coronavirus     -> sars            (compound)
sars            -> detail          (compound)
cov             -> detail          (compound)
epidemiological -> detail          (amod)
clinical        -> report          (amod)
characteristic  -> report          (amod)
patient         -> report          (compound)
covid           -> report          (compound)
report          -> illness         (compound)
risk            -> factor          (compound)
factor          -> illness         (compound)
mortality       -> illness         (compound)
detail          -> illness         (compound)
clinical        -> course          (amod)
course          -> illness         (compound)
illness         -> include         (nsubj)
include         -> ROOT            (root)
viral           -> study           (amod)
shed            -> describe        (compound)
well            -> describe        (advmod)
describe        -> study           (amod)
method          -> study           (compound)
retrospective   -> study           (compound)
multicentre     -> study           (compound)
cohort          -> study           (compound)
study           -> include         (nsubj)
include         -> include         (ccomp)
adult           -> year            (compound)
inpatient       -> year            (amod)
year            -> old             (obl:unmarked)
old             -> confirm         (amod)
laboratory      -> confirm         (compound)
confirm         -> die             (obj)
covid           -> hospital        (compound)
jinyintan       -> hospital        (compound)
hospital        -> discharge       (compound)
wuhan           -> discharge       (compound)
pulmonary       -> discharge       (amod)
hospital        -> discharge       (compound)
wuhan           -> discharge       (compound)
china           -> discharge       (compound)
discharge       -> die             (nsubj)
die             -> include         (parataxis)
jan             -> demographic     (compound)
demographic     -> data            (compound)
clinical        -> data            (amod)
treatment       -> data            (compound)
laboratory      -> data            (compound)
data            -> include         (nsubj)
include         -> include         (parataxis)
serial          -> extract         (amod)
sample          -> extract         (compound)
viral           -> extract         (amod)
rna             -> extract         (compound)
detection       -> extract         (compound)
extract         -> include         (obj)
electronic      -> compare         (amod)
medical         -> compare         (amod)
record          -> survivor        (compound)
compare         -> method          (compound)
survivor        -> method          (compound)
non             -> use             (compound)
survivor        -> method          (compound)
use             -> method          (compound)
univariable     -> method          (amod)
multivariable   -> method          (amod)
logistic        -> method          (amod)
regression      -> method          (compound)
method          -> find            (obj)
explore         -> include         (parataxis)
risk            -> factor          (compound)
factor          -> death           (compound)
associate       -> death           (compound)
hospital        -> death           (compound)
death           -> explore         (obj)
find            -> explore         (conj)
patient         -> jinyintan       (compound)
jinyintan       -> hospital        (compound)
hospital        -> hospital        (compound)
wuhan           -> hospital        (compound)
pulmonary       -> hospital        (amod)
hospital        -> include         (nsubj)
include         -> explore         (parataxis)
study           -> discharge       (compound)
discharge       -> die             (obj)
die             -> include         (ccomp)
hospital        -> patient         (compound)
patient         -> patient         (compound)
comorbidity     -> patient         (compound)
hypertension    -> patient         (compound)
common          -> patient         (amod)
patient         -> die             (obj)
follow          -> patient         (amod)
diabetes        -> patient         (compound)
patient         -> show            (compound)
coronary        -> show            (compound)
heart           -> disease         (compound)
disease         -> show            (compound)
patient         -> odds            (compound)
multivariable   -> odds            (amod)
regression      -> show            (compound)
show            -> associate       (compound)
increase        -> odds            (compound)
odds            -> ratio           (compound)
hospital        -> ratio           (compound)
death           -> ratio           (compound)
associate       -> ci              (compound)
older           -> ratio           (amod)
age             -> ratio           (compound)
odds            -> ratio           (compound)
ratio           -> p               (compound)
ci              -> higher          (compound)
per             -> year            (case)
year            -> ci              (nmod)
increase        -> ci              (nmod)
p               -> assessment      (nmod:unmarked)
higher          -> p               (amod)
sequential      -> dimer           (amod)
organ           -> failure         (compound)
failure         -> score           (compound)
assessment      -> score           (compound)
sofa            -> score           (compound)
score           -> p               (compound)
p               -> p               (compound)
dimer           -> duration        (compound)
greater         -> duration        (amod)
g               -> duration        (compound)
ml              -> duration        (compound)
p               -> viral           (compound)
admission       -> sars            (compound)
median          -> sars            (compound)
duration        -> sars            (compound)
viral           -> sars            (compound)
shed            -> sars            (compound)
day             -> sars            (compound)
iqr             -> sars            (compound)
survivor        -> sars            (compound)
sars            -> duration        (compound)
cov             -> duration        (compound)
detectable      -> duration        (amod)
death           -> duration        (compound)
non             -> duration        (compound)
survivor        -> duration        (compound)
longest         -> observe         (amod)
observe         -> duration        (compound)
duration        -> help            (nsubj)
viral           -> potential       (amod)
shed            -> day             (compound)
survivor        -> day             (compound)
day             -> factor          (compound)
interpretation  -> factor          (compound)
potential       -> age             (compound)
risk            -> factor          (compound)
factor          -> help            (nsubj)
older           -> age             (amod)
age             -> ml              (compound)
high            -> ml              (amod)
sofa            -> score           (compound)
score           -> ml              (compound)
dimer           -> ml              (compound)
greater         -> ml              (amod)
g               -> ml              (compound)
ml              -> help            (nsubj)
could           -> help            (aux)
help            -> include         (parataxis)
clinician       -> help            (obj)
identify        -> help            (xcomp)
patient         -> stage           (amod)
poor            -> stage           (amod)
prognosis       -> stage           (compound)
early           -> stage           (amod)
stage           -> identify        (obj)
prolong         -> identify        (xcomp)
viral           -> shed            (amod)
shed            -> prolong         (obj)
provide         -> identify        (xcomp)
rationale       -> isolation       (compound)
strategy        -> isolation       (compound)
isolation       -> provide         (obj)
infect          -> provide         (xcomp)
patient         -> intervention    (compound)
optimal         -> intervention    (amod)
antiviral       -> intervention    (amod)
intervention    -> fund            (compound)
future          -> fund            (amod)
fund            -> academy         (compound)
chinese         -> academy         (amod)
academy         -> innovation      (compound)
medical         -> innovation      (amod)
science         -> innovation      (compound)
innovation      -> grant           (compound)
fund            -> grant           (compound)
medical         -> science         (amod)
science         -> grant           (compound)
national        -> grant           (amod)
science         -> grant           (compound)
grant           -> distinguish     (obj)
distinguish     -> infect          (conj)
young           -> scholar         (amod)
scholar         -> program         (compound)
national        -> program         (amod)
key             -> program         (amod)
research        -> development     (compound)
development     -> program         (compound)
program         -> project         (compound)
china           -> project         (compound)
beijing         -> project         (compound)
science         -> technology      (compound)
technology      -> project         (compound)
project         -> distinguish     (obj)
major           -> development     (amod)
project         -> development     (compound)
national        -> technology      (amod)
science         -> technology      (compound)
technology      -> development     (compound)
new             -> development     (amod)
drug            -> creation        (compound)
creation        -> development     (compound)
development     -> project         (appos)

####################################################################################################
DOCUMENT 2
####################################################################################################

==========================================================================================
Sentence 1: diabetes statistic cdc glucagon megaroll infocorn oil cocaine effective reinforcer data analysis student mark descriptive statisticsfriedman test wikipediadownload free ebook pdf epub tuebl mobistatistics stat university pennsylvaniaerik sudderth donald bren school information bootstrapping statistic wikipediarunze li homepage pennsylvania state universitycausal inference statistic overviewfind doctor clinician researcher nurse etdaundergraduate course description statistic departmentcomputation different effect size like f r biography activity susan holmesfaculty department statisticsnonparametric method definition investopediastatistics final exam flashcard quizlettest di kruskal wallis wikipediadepartment statistic data science carnegie use statistic social science emerald insightbehavioral genetics psychology oxford bibliographiesinterpreting statistic introduction statistic g power flexible statistical power analysis program lifetime data analysis home springerwilcoxon test definition investopediagraphpad prism statistic guide interpret result log bacbnonparametric test boston universitytopic introduction measurement statisticsstatistics assignment help statistic homework helpstatistics stat iowa state university catalogeric j tchetgen tchetgen department statistic journal american statistical associationwhat rationale behind magic number

Constituency Parse Tree:

# **Following Questions must answer using AI assitance**

#Question 4 (20 points).

Q4. (PART-1)
Web scraping data from the GitHub Marketplace to gather details about popular actions. Using Python, the process begins by sending HTTP requests to multiple pages of the marketplace (1000 products), handling pagination through dynamic page numbers. The key details extracted include the product name, a short description, and the URL.

 The extracted data is stored in a structured CSV format with columns for product name, description, URL, and page number. A time delay is introduced between requests to avoid server overload. ChatGPT can assist by helping with the parsing of HTML, error handling, and generating reports based on the data collected.

 The goal is to complete the scraping within a specified time limit, ensuring that the process is efficient and adheres to GitHub’s usage guidelines.

(PART -2)

1.   **Preprocess Data**: Clean the text by tokenizing, removing stopwords, and converting to lowercase.

2. Perform **Data Quality** operations.


Preprocessing:
Preprocessing involves cleaning the text by removing noise such as special characters, HTML tags, and unnecessary whitespace. It also includes tasks like tokenization, stopword removal, and lemmatization to standardize the text for analysis.

Data Quality:
Data quality checks ensure completeness, consistency, and accuracy by verifying that all required columns are filled and formatted correctly. Additionally, it involves identifying and removing duplicates, handling missing values, and ensuring the data reflects the true content accurately.

Github MarketPlace page:
https://github.com/marketplace?type=actions

In [64]:
!pip -q install beautifulsoup4 lxml pandas requests tqdm

In [65]:
import re
import time
import random
import requests
import pandas as pd
from bs4 import BeautifulSoup
from tqdm.auto import tqdm
from urllib.parse import urljoin

In [66]:
BASE = "https://github.com/marketplace"
START_URL = "https://github.com/marketplace?type=actions&sort=popularity"  # Popularity is shown on the page UI
TARGET_PRODUCTS = 1000
MAX_PAGES_HARD_CAP = 500  # page UI shows it can go very high (e.g., ...500) :contentReference[oaicite:2]{index=2}

DELAY_RANGE = (1.0, 1.8)      # polite delay between page requests
RETRY_LIMIT = 4

session = requests.Session()
session.headers.update({
    "User-Agent": "UNT-DS-WebScrape-Assignment/1.0 (polite; educational)",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
})

def fetch_html(url: str, retry_limit: int = RETRY_LIMIT) -> str:
    last_err = None
    for attempt in range(1, retry_limit + 1):
        try:
            r = session.get(url, timeout=30)
            if r.status_code == 429:
                backoff = 2 ** attempt + random.random()
                print(f"[429] Rate limited. Sleeping {backoff:.1f}s and retrying...")
                time.sleep(backoff)
                continue
            if r.status_code in (500, 502, 503, 504):
                backoff = 2 ** attempt + random.random()
                print(f"[{r.status_code}] Server error. Sleeping {backoff:.1f}s and retrying...")
                time.sleep(backoff)
                continue
            r.raise_for_status()
            return r.text
        except Exception as e:
            last_err = e
            backoff = 1.5 ** attempt + random.random()
            print(f"[WARN] Attempt {attempt}/{retry_limit} failed: {e}. Sleeping {backoff:.1f}s...")
            time.sleep(backoff)
    raise RuntimeError(f"Failed to fetch after {retry_limit} retries. Last error: {last_err}")

def get_card_container(h3_tag):
    card = h3_tag
    while card.parent:
        parent = card.parent
        if len(parent.select('h3 a[href^="/marketplace/actions/"]')) > 1:
            break
        card = parent
    return card

def extract_description_from_card(card, name):
    lines = [ln.strip() for ln in card.get_text("\n", strip=True).splitlines() if ln.strip()]

    # Find "Action" marker and pick the next meaningful line as description
    markers = {"action", "actions"}
    for i, ln in enumerate(lines):
        if ln.strip().lower() in markers:
            # look at next few lines after "Action"
            for cand in lines[i+1:i+8]:
                c = cand.strip()
                low = c.lower()
                if not c:
                    continue
                if low in markers:
                    continue
                if c == name:
                    continue
                if low.startswith("by "):
                    continue
                # keep it "short description"-ish
                if 10 <= len(c) <= 280:
                    return c
            break

    # fallback: first decent line that isn't the name or boilerplate
    for c in lines:
        low = c.lower()
        if c == name or low in markers or low.startswith("by "):
            continue
        if 10 <= len(c) <= 280:
            return c

    return ""

def parse_marketplace_actions(html: str, page_number: int) -> list[dict]:
    soup = BeautifulSoup(html, "lxml")
    main = soup.find("main") or soup

    items = []
    for a in main.select('h3 a[href^="/marketplace/actions/"]'):
        href = (a.get("href") or "").strip()
        if not href or not re.match(r"^/marketplace/actions/[^/?#]+$", href):
            continue

        name = a.get_text(" ", strip=True)
        if not name:
            continue

        h3 = a.find_parent("h3") or a
        card = get_card_container(h3)

        desc = extract_description_from_card(card, name)
        full_url = urljoin("https://github.com", href)

        items.append({
            "product_name": name,
            "description": desc,
            "url": full_url,
            "page_number": page_number
        })

    # de-dup within page by URL
    dedup = {}
    for it in items:
        dedup[it["url"]] = it
    return list(dedup.values())

def scrape_actions_1000():
    results = []
    seen = set()

    for page in tqdm(range(1, MAX_PAGES_HARD_CAP + 1), desc="Scraping pages"):
        url = f"{BASE}?type=actions&sort=popularity&page={page}"
        html = fetch_html(url)
        page_items = parse_marketplace_actions(html, page)

        if not page_items:
            print(f"[STOP] No items found on page {page}.")
            break

        for it in page_items:
            if it["url"] in seen:
                continue
            seen.add(it["url"])
            results.append(it)
            if len(results) >= TARGET_PRODUCTS:
                break

        if len(results) >= TARGET_PRODUCTS:
            break

        time.sleep(random.uniform(*DELAY_RANGE))

    return results

actions = scrape_actions_1000()
df_raw = pd.DataFrame(actions)

print("Scraped rows:", len(df_raw))
df_raw.head(5)

Scraping pages:   0%|          | 0/500 [00:00<?, ?it/s]

[429] Rate limited. Sleeping 2.7s and retrying...
[429] Rate limited. Sleeping 4.2s and retrying...
[429] Rate limited. Sleeping 8.4s and retrying...
Scraped rows: 1000

,product_name,description,url,page_number
0,TruffleHog OSS,Find and verify leaked credentials in your sou...,https://github.com/marketplace/actions/truffle...,1
1,Metrics embed,An infographics generator with 40+ plugins and...,https://github.com/marketplace/actions/metrics...,1
2,yq - portable yaml processor,"create, read, update, delete, merge, validate ...",https://github.com/marketplace/actions/yq-port...,1
3,Super-Linter,Super-linter is a ready-to-run collection of l...,https://github.com/marketplace/actions/super-l...,1
4,Rebuild Armbian and Kernel,"Support Amlogic, Rockchip and Allwinner boxes",https://github.com/marketplace/actions/rebuild...,1

In [67]:
import re
import pandas as pd
import nltk
nltk.download("stopwords")
nltk.download("wordnet")

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def basic_text_clean(s: str) -> str:
    s = s or ""
    s = s.lower()
    s = re.sub(r"<[^>]+>", " ", s)
    s = re.sub(r"[^a-z\s]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

def tokenize(s: str) -> list[str]:
    return [t for t in s.split() if t]

def remove_stopwords(tokens: list[str]) -> list[str]:
    return [t for t in tokens if t not in stop_words]

def lemmatize_tokens(tokens: list[str]) -> list[str]:
    return [lemmatizer.lemmatize(t) for t in tokens]

# ---- Build df_clean ----
df_clean = df_raw.copy()
df_clean["product_name"] = df_clean["product_name"].fillna("").astype(str).str.strip()
df_clean["description"] = df_clean["description"].fillna("").astype(str)

df_clean["desc_clean"] = df_clean["description"].apply(basic_text_clean)
df_clean["tokens"] = df_clean["desc_clean"].apply(tokenize)
df_clean["tokens_no_stop"] = df_clean["tokens"].apply(remove_stopwords)
df_clean["tokens_lemma"] = df_clean["tokens_no_stop"].apply(lemmatize_tokens)
df_clean["desc_final"] = df_clean["tokens_lemma"].apply(lambda toks: " ".join(toks))

# ---- Data quality fixes ----
df_clean = df_clean[df_clean["product_name"].str.len() > 0].copy()
df_clean = df_clean[df_clean["url"].fillna("").astype(str).str.len() > 0].copy()
df_clean["page_number"] = pd.to_numeric(df_clean["page_number"], errors="coerce")
df_clean = df_clean.dropna(subset=["page_number"])
df_clean["page_number"] = df_clean["page_number"].astype(int)

df_clean = df_clean.drop_duplicates(subset=["url"]).reset_index(drop=True)

print("df_clean rows:", len(df_clean))
df_clean[["product_name","description","desc_final","url","page_number"]].head(5)

df_clean rows: 1000

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,product_name,description,desc_final,url,page_number
0,TruffleHog OSS,Find and verify leaked credentials in your sou...,find verify leaked credential source code,https://github.com/marketplace/actions/truffle...,1
1,Metrics embed,An infographics generator with 40+ plugins and...,infographics generator plugins option display ...,https://github.com/marketplace/actions/metrics...,1
2,yq - portable yaml processor,"create, read, update, delete, merge, validate ...",create read update delete merge validate yaml,https://github.com/marketplace/actions/yq-port...,1
3,Super-Linter,Super-linter is a ready-to-run collection of l...,super linter ready run collection linters code...,https://github.com/marketplace/actions/super-l...,1
4,Rebuild Armbian and Kernel,"Support Amlogic, Rockchip and Allwinner boxes",support amlogic rockchip allwinner box,https://github.com/marketplace/actions/rebuild...,1

In [68]:
df_raw.to_csv("github_marketplace_actions_raw.csv", index=False)
df_clean.to_csv("github_marketplace_actions_cleaned.csv", index=False)
print("Saved both CSVs.")

Saved both CSVs.

In [69]:
def dq_summary(d):
    return pd.DataFrame([{
        "rows": len(d),
        "missing_name": int((d["product_name"].fillna("").str.strip() == "").sum()),
        "missing_desc": int((d["description"].fillna("").str.strip() == "").sum()),
        "missing_url": int((d["url"].fillna("").str.strip() == "").sum()),
        "dup_url": int(d.duplicated("url").sum()),
        "invalid_url": int((~d["url"].astype(str).str.startswith("https://github.com/marketplace/actions/")).sum()),
        "desc_too_short(<10)": int((d["description"].fillna("").str.len() < 10).sum()),
    }])

print("RAW DQ:")
display(dq_summary(df_raw))

print("CLEAN DQ:")
display(dq_summary(df_clean))

RAW DQ:

,rows,missing_name,missing_desc,missing_url,dup_url,invalid_url,desc_too_short(<10)
0,1000,0,11,0,0,0,11

CLEAN DQ:

,rows,missing_name,missing_desc,missing_url,dup_url,invalid_url,desc_too_short(<10)
0,1000,0,11,0,0,0,11

In [70]:
df_clean[["product_name","description","desc_clean","desc_final"]].head(10)

,product_name,description,desc_clean,desc_final
0,TruffleHog OSS,Find and verify leaked credentials in your sou...,find and verify leaked credentials in your sou...,find verify leaked credential source code
1,Metrics embed,An infographics generator with 40+ plugins and...,an infographics generator with plugins and opt...,infographics generator plugins option display ...
2,yq - portable yaml processor,"create, read, update, delete, merge, validate ...",create read update delete merge validate and d...,create read update delete merge validate yaml
3,Super-Linter,Super-linter is a ready-to-run collection of l...,super linter is a ready to run collection of l...,super linter ready run collection linters code...
4,Rebuild Armbian and Kernel,"Support Amlogic, Rockchip and Allwinner boxes",support amlogic rockchip and allwinner boxes,support amlogic rockchip allwinner box
5,Gosec Security Checker,Runs the gosec security checker,runs the gosec security checker,run gosec security checker
6,Checkout,Checkout a Git repository at a particular version,checkout a git repository at a particular version,checkout git repository particular version
7,OpenCommit — improve commits with AI 🧙,Replaces lame commit messages with meaningful ...,replaces lame commit messages with meaningful ...,replaces lame commit message meaningful ai gen...
8,SSH Remote Commands,Executing remote ssh commands,executing remote ssh commands,executing remote ssh command
9,Claude Code Action Official,General-purpose Claude agent for GitHub PRs an...,general purpose claude agent for github prs an...,general purpose claude agent github pr issue a...

In [71]:
print("Total actions scraped:", len(df_raw))
print("Pages used:", df_raw["page_number"].nunique())
print("Min page:", df_raw["page_number"].min(), "Max page:", df_raw["page_number"].max())
df_raw[["product_name","description","url","page_number"]].head(10)

Total actions scraped: 1000
Pages used: 51
Min page: 1 Max page: 51

,product_name,description,url,page_number
0,TruffleHog OSS,Find and verify leaked credentials in your sou...,https://github.com/marketplace/actions/truffle...,1
1,Metrics embed,An infographics generator with 40+ plugins and...,https://github.com/marketplace/actions/metrics...,1
2,yq - portable yaml processor,"create, read, update, delete, merge, validate ...",https://github.com/marketplace/actions/yq-port...,1
3,Super-Linter,Super-linter is a ready-to-run collection of l...,https://github.com/marketplace/actions/super-l...,1
4,Rebuild Armbian and Kernel,"Support Amlogic, Rockchip and Allwinner boxes",https://github.com/marketplace/actions/rebuild...,1
5,Gosec Security Checker,Runs the gosec security checker,https://github.com/marketplace/actions/gosec-s...,1
6,Checkout,Checkout a Git repository at a particular version,https://github.com/marketplace/actions/checkout,1
7,OpenCommit — improve commits with AI 🧙,Replaces lame commit messages with meaningful ...,https://github.com/marketplace/actions/opencom...,1
8,SSH Remote Commands,Executing remote ssh commands,https://github.com/marketplace/actions/ssh-rem...,1
9,Claude Code Action Official,General-purpose Claude agent for GitHub PRs an...,https://github.com/marketplace/actions/claude-...,1

In [72]:
df_clean[["product_name","description","desc_clean","desc_final"]].head(10)

,product_name,description,desc_clean,desc_final
0,TruffleHog OSS,Find and verify leaked credentials in your sou...,find and verify leaked credentials in your sou...,find verify leaked credential source code
1,Metrics embed,An infographics generator with 40+ plugins and...,an infographics generator with plugins and opt...,infographics generator plugins option display ...
2,yq - portable yaml processor,"create, read, update, delete, merge, validate ...",create read update delete merge validate and d...,create read update delete merge validate yaml
3,Super-Linter,Super-linter is a ready-to-run collection of l...,super linter is a ready to run collection of l...,super linter ready run collection linters code...
4,Rebuild Armbian and Kernel,"Support Amlogic, Rockchip and Allwinner boxes",support amlogic rockchip and allwinner boxes,support amlogic rockchip allwinner box
5,Gosec Security Checker,Runs the gosec security checker,runs the gosec security checker,run gosec security checker
6,Checkout,Checkout a Git repository at a particular version,checkout a git repository at a particular version,checkout git repository particular version
7,OpenCommit — improve commits with AI 🧙,Replaces lame commit messages with meaningful ...,replaces lame commit messages with meaningful ...,replaces lame commit message meaningful ai gen...
8,SSH Remote Commands,Executing remote ssh commands,executing remote ssh commands,executing remote ssh command
9,Claude Code Action Official,General-purpose Claude agent for GitHub PRs an...,general purpose claude agent for github prs an...,general purpose claude agent github pr issue a...

In [73]:
df_clean.sample(5, random_state=42)[["product_name","description","desc_final"]]

,product_name,description,desc_final
521,LaTeX compilation,"Compiles latex documents using pdflatex, luala...",compiles latex document using pdflatex lualate...
737,golang-govulncheck-action,Run govulncheck,run govulncheck
740,Frogo-Keyboard-Open-Source,Full and Clear Documentation,full clear documentation
660,cls3-action,Run cls3 in GitHub Actions,run cl github action
411,MongoDB in GitHub Actions,Start a MongoDB server (on default port 27017 ...,start mongodb server default port custom port

In [74]:
def dq_summary(d):
    return pd.DataFrame([{
        "rows": len(d),
        "missing_product_name": int((d["product_name"].fillna("").str.strip() == "").sum()),
        "missing_description": int((d["description"].fillna("").str.strip() == "").sum()),
        "missing_url": int((d["url"].fillna("").str.strip() == "").sum()),
        "duplicate_urls": int(d.duplicated("url").sum()),
        "invalid_url_prefix": int((~d["url"].astype(str).str.startswith("https://github.com/marketplace/actions/")).sum()),
        "empty_desc_rate": float((d["description"].fillna("").str.strip() == "").mean()),
    }])

print("RAW Data Quality Summary")
display(dq_summary(df_raw))

print("CLEAN Data Quality Summary")
display(dq_summary(df_clean))

RAW Data Quality Summary

,rows,missing_product_name,missing_description,missing_url,duplicate_urls,invalid_url_prefix,empty_desc_rate
0,1000,0,11,0,0,0,0.011

CLEAN Data Quality Summary

,rows,missing_product_name,missing_description,missing_url,duplicate_urls,invalid_url_prefix,empty_desc_rate
0,1000,0,11,0,0,0,0.011

In [75]:
df_raw.to_csv("github_marketplace_actions_raw.csv", index=False)
df_clean.to_csv("github_marketplace_actions_cleaned.csv", index=False)
print("Saved: github_marketplace_actions_raw.csv")
print("Saved: github_marketplace_actions_cleaned.csv")

Saved: github_marketplace_actions_raw.csv
Saved: github_marketplace_actions_cleaned.csv

In [76]:
df_raw.to_csv("github_marketplace_actions_raw.csv", index=False)
df_clean.to_csv("github_marketplace_actions_cleaned.csv", index=False)
print("Saved: github_marketplace_actions_raw.csv")
print("Saved: github_marketplace_actions_cleaned.csv")

Saved: github_marketplace_actions_raw.csv
Saved: github_marketplace_actions_cleaned.csv

In [77]:
print("Average description length:", df_raw["description"].fillna("").str.len().mean())
print("Median description length:", df_raw["description"].fillna("").str.len().median())

Average description length: 60.014
Median description length: 55.5

In [78]:
from collections import Counter

all_tokens = [t for row in df_clean["tokens_lemma"] for t in row]  # tokens_lemma is a list
Counter(all_tokens).most_common(20)

[('github', 354),
 ('action', 315),
 ('run', 117),
 ('request', 89),
 ('pull', 85),
 ('code', 84),
 ('file', 81),
 ('build', 68),
 ('workflow', 63),
 ('using', 58),
 ('release', 49),
 ('deploy', 49),
 ('repository', 47),
 ('automatically', 47),
 ('issue', 46),
 ('pr', 44),
 ('check', 43),
 ('project', 42),
 ('version', 40),
 ('install', 40)]

#Question 5 (20 points)

PART 1:
Web Scrape  tweets from Twitter using the Tweepy API, specifically targeting hashtags related to subtopics (machine learning or artificial intelligence.)
The extracted data includes the tweet ID, username, and text.

Part 2:
Perform data cleaning procedures

A final data quality check ensures the completeness and consistency of the dataset. The cleaned data is then saved into a CSV file for further analysis.


**Note**

1.   Follow tutorials provided in canvas to obtain api keys. Use ChatGPT to get the code. Make sure the file is downloaded and saved.
2.   Make sure you divide GPT code as shown in tutorials, dont make multiple requestes.

In [11]:
!pip -q install pandas nltk beautifulsoup4 lxml

In [12]:
import re
import time
import random
import requests
import pandas as pd
from bs4 import BeautifulSoup
from google.colab import files
from collections import Counter

In [13]:
TARGET_ROWS = 1000
HITS_PER_PAGE = 100          # 100 is reliable; API supports pagination via page/hitsPerPage :contentReference[oaicite:1]{index=1}
DELAY_RANGE = (0.8, 1.4)     # polite delay

# “Hashtag-like” topics (align with ML/AI subtopics)
QUERIES = [
    "#machinelearning",
    "#ai",
    "machine learning",
    "artificial intelligence",
    "deep learning",
    "llm",
    "nlp",
]

BASE_URL = "https://hn.algolia.com/api/v1/search_by_date"  # documented endpoint :contentReference[oaicite:2]{index=2}

In [14]:
session = requests.Session()
session.headers.update({"User-Agent": "UNT-DS-Q5-API-Demo/1.0 (educational)"})

def fetch_page(query: str, page: int, hits_per_page: int = 100, tags: str = "comment", retry_limit: int = 4):
    params = {
        "query": query,
        "tags": tags,
        "page": page,
        "hitsPerPage": hits_per_page,
    }

    last_err = None
    for attempt in range(1, retry_limit + 1):
        try:
            r = session.get(BASE_URL, params=params, timeout=30)
            if r.status_code == 429:
                wait = 2 ** attempt + random.random()
                print(f"[429] Rate limited. Sleeping {wait:.1f}s...")
                time.sleep(wait)
                continue
            r.raise_for_status()
            return r.json()
        except Exception as e:
            last_err = e
            wait = 1.5 ** attempt + random.random()
            print(f"[WARN] attempt {attempt}/{retry_limit} failed: {e}. Sleeping {wait:.1f}s...")
            time.sleep(wait)
    raise RuntimeError(f"Failed after retries. Last error: {last_err}")

In [15]:
def html_to_text(s: str) -> str:
    # comment_text from HN often contains HTML tags
    if not s:
        return ""
    return BeautifulSoup(s, "lxml").get_text(" ", strip=True)

rows = []
seen_ids = set()

for q in QUERIES:
    page = 0
    print("\nQuery:", q)

    while len(rows) < TARGET_ROWS:
        data = fetch_page(q, page, hits_per_page=HITS_PER_PAGE, tags="comment")
        hits = data.get("hits", [])
        if not hits:
            break

        for h in hits:
            oid = h.get("objectID", "")
            if not oid:
                continue
            if oid in seen_ids:
                continue
            seen_ids.add(oid)

            username = h.get("author", "") or ""
            text = html_to_text(h.get("comment_text", "") or "")

            # Keep only meaningful text
            if len(text.strip()) < 20:
                continue

            rows.append({
                "tweet_id": oid,                 # tweet id equivalent
                "username": username,            # user name equivalent
                "text": text,                    # tweet text equivalent
                "query_used": q,
                "created_at": h.get("created_at", None),
                "url": h.get("url", None),
            })

            if len(rows) >= TARGET_ROWS:
                break

        page += 1
        print(f"Collected {len(rows)}/{TARGET_ROWS} | page={page}")

        # polite delay
        time.sleep(random.uniform(*DELAY_RANGE))

    if len(rows) >= TARGET_ROWS:
        break

df_raw = pd.DataFrame(rows)
print("\nRAW rows:", len(df_raw))
df_raw.head(10)

Query: #machinelearning
Collected 81/1000 | page=1

Query: #ai
Collected 178/1000 | page=1
Collected 266/1000 | page=2
Collected 353/1000 | page=3
Collected 450/1000 | page=4
Collected 486/1000 | page=5

Query: machine learning
Collected 586/1000 | page=1
Collected 686/1000 | page=2
Collected 786/1000 | page=3
Collected 886/1000 | page=4
Collected 986/1000 | page=5
Collected 1000/1000 | page=6

RAW rows: 1000

,tweet_id,username,text,query_used,created_at,url
0,44814710,idebasispaul,Whether you’re a beginner or want to level up ...,#machinelearning,2025-08-06T17:07:48Z,None
1,44784339,idebasispaul,"Hey friends,\nI'm super excited to share somet...",#machinelearning,2025-08-04T11:25:13Z,None
2,44756123,Mignet,*Building an AI-Powered Document Understanding...,#machinelearning,2025-08-01T12:58:41Z,None
3,44645342,bmacho,Overfitting is achieving better and better sco...,#machinelearning,2025-07-22T10:50:07Z,None
4,44286531,zz99mz,Hi Hacker News! I’m Michael Zimmerman from Ver...,#machinelearning,2025-06-16T04:04:47Z,None
5,44226147,GremlinGPT,Just shipped a fully-wired local AI stack:\n •...,#machinelearning,2025-06-09T16:28:55Z,None
6,44148944,Voice_of_Void,"Comparing AI like Grok, Claude, or Llama is li...",#machinelearning,2025-06-01T06:04:04Z,None
7,44015001,Voice_of_Void,Geoffrey Hinton claims AI might take over (20%...,#machinelearning,2025-05-17T15:27:45Z,None
8,43957812,Voice_of_Void,"SingularityForge’s latest, AI and Improvisatio...",#machinelearning,2025-05-11T22:37:45Z,None
9,43855494,Voice_of_Void,New research reveals how phase transitions in ...,#machinelearning,2025-05-01T09:40:13Z,None

In [16]:
raw_path = "q5_hn_raw.csv"
df_raw.to_csv(raw_path, index=False)
print("Saved:", raw_path)

Saved: q5_hn_raw.csv

In [17]:
import nltk
nltk.download("stopwords")
nltk.download("wordnet")

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [18]:
def clean_text(s: str) -> str:
    s = s or ""
    s = s.lower()
    s = re.sub(r"http\S+|www\.\S+", " ", s)   # URLs
    s = re.sub(r"[^a-z\s]", " ", s)           # remove numbers + punctuation/special chars
    s = re.sub(r"\s+", " ", s).strip()
    return s

def preprocess(s: str) -> str:
    s = clean_text(s)
    toks = [t for t in s.split() if t and t not in stop_words]
    lemmas = [lemmatizer.lemmatize(t) for t in toks]
    return " ".join(lemmas)

df_clean = df_raw.copy()
df_clean["text_clean"] = df_clean["text"].astype(str).apply(preprocess)

# Output evidence (required-looking)
df_clean[["text", "text_clean"]].head(10)

,text,text_clean
0,Whether you’re a beginner or want to level up ...,whether beginner want level dev skill daysofco...
1,"Hey friends,\nI'm super excited to share somet...",hey friend super excited share something game ...
2,*Building an AI-Powered Document Understanding...,building ai powered document understanding too...
3,Overfitting is achieving better and better sco...,overfitting achieving better better score trai...
4,Hi Hacker News! I’m Michael Zimmerman from Ver...,hi hacker news michael zimmerman verso industr...
5,Just shipped a fully-wired local AI stack:\n •...,shipped fully wired local ai stack local mistr...
6,"Comparing AI like Grok, Claude, or Llama is li...",comparing ai like grok claude llama like judgi...
7,Geoffrey Hinton claims AI might take over (20%...,geoffrey hinton claim ai might take chance say...
8,"SingularityForge’s latest, AI and Improvisatio...",singularityforge latest ai improvisation logic...
9,New research reveals how phase transitions in ...,new research reveals phase transition llm like...

In [19]:
def dq_report(d: pd.DataFrame) -> pd.DataFrame:
    return pd.DataFrame([{
        "rows": len(d),
        "missing_tweet_id": int((d["tweet_id"].fillna("").astype(str).str.strip() == "").sum()),
        "missing_username": int((d["username"].fillna("").astype(str).str.strip() == "").sum()),
        "missing_text": int((d["text"].fillna("").astype(str).str.strip() == "").sum()),
        "missing_text_clean": int((d["text_clean"].fillna("").astype(str).str.strip() == "").sum()),
        "duplicate_tweet_id": int(d.duplicated("tweet_id").sum()),
        "avg_clean_len": float(d["text_clean"].fillna("").astype(str).str.len().mean()),
    }])

print("=== BEFORE FIXES ===")
display(dq_report(df_clean))

# Fixes
df_clean["tweet_id"] = df_clean["tweet_id"].astype(str).str.strip()
df_clean["username"] = df_clean["username"].fillna("").astype(str).str.strip()
df_clean["text"] = df_clean["text"].fillna("").astype(str)
df_clean["text_clean"] = df_clean["text_clean"].fillna("").astype(str)

df_clean = df_clean[df_clean["tweet_id"].str.len() > 0].copy()
df_clean = df_clean[df_clean["text"].str.len() > 0].copy()
df_clean = df_clean.drop_duplicates(subset=["tweet_id"]).reset_index(drop=True)

print("=== AFTER FIXES ===")
display(dq_report(df_clean))

df_clean.head(5)

=== BEFORE FIXES ===

,rows,missing_tweet_id,missing_username,missing_text,missing_text_clean,duplicate_tweet_id,avg_clean_len
0,1000,0,0,0,1,0,605.069

=== AFTER FIXES ===

,rows,missing_tweet_id,missing_username,missing_text,missing_text_clean,duplicate_tweet_id,avg_clean_len
0,1000,0,0,0,1,0,605.069

,tweet_id,username,text,query_used,created_at,url,text_clean
0,44814710,idebasispaul,Whether you’re a beginner or want to level up ...,#machinelearning,2025-08-06T17:07:48Z,None,whether beginner want level dev skill daysofco...
1,44784339,idebasispaul,"Hey friends,\nI'm super excited to share somet...",#machinelearning,2025-08-04T11:25:13Z,None,hey friend super excited share something game ...
2,44756123,Mignet,*Building an AI-Powered Document Understanding...,#machinelearning,2025-08-01T12:58:41Z,None,building ai powered document understanding too...
3,44645342,bmacho,Overfitting is achieving better and better sco...,#machinelearning,2025-07-22T10:50:07Z,None,overfitting achieving better better score trai...
4,44286531,zz99mz,Hi Hacker News! I’m Michael Zimmerman from Ver...,#machinelearning,2025-06-16T04:04:47Z,None,hi hacker news michael zimmerman verso industr...

In [20]:
clean_path = "q5_hn_cleaned.csv"
df_clean.to_csv(clean_path, index=False)
print("Saved:", clean_path)

files.download(clean_path)

Saved: q5_hn_cleaned.csv

**X/Twitter API access is now paid.** Per instructor guidance, I used the public Hacker News Search API (Algolia) to demonstrate authenticated-style API usage and data collection. I collected post IDs (tweet_id equivalent), usernames, and text for ML/AI-related keyword queries, cleaned the text, ran data quality checks, and exported a cleaned CSV.

# Mandatory Question (5 points)

Provide your thoughts on the assignment. What did you find challenging, and what aspects did you enjoy? Your opinion on the provided time to complete the assignment.

# **My Answer**
I enjoyed working with real text data and seeing how cleaning changes the results. The most challenging part was collecting data because scraping/API access can break unexpectedly, and Twitter/X API limits required using an alternative. The time was reasonable if started early, but debugging can be time-consuming.