<a href="https://colab.research.google.com/github/shreeyashbaran/Info-5731/blob/main/In_Class_Exercise_BERTopic_Topic_Modeling_FINAL_Shreeyash%20Baranwal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In-Class Exercise — BERTopic Topic Modeling

**Time:** 20 minutes  
**Points:** 10  

**Dataset file:** `bertopic_class_data_student.csv`

Upload the dataset from Canvas, then complete the questions below.

### Expected columns
- `text`
- `clean_text`
- `date`

### Important note
Use the **`clean_text`** column for topic modeling.

In [1]:
# Run this cell only if BERTopic is not already installed in your environment.
!pip -q install bertopic

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 2.7 MB/s eta 0:00:00

In [2]:
# Upload the dataset file from your computer (Google Colab)
from google.colab import files

uploaded = files.upload()
filename = next(iter(uploaded))
print("Uploaded file name:", filename)

Saving bertopic_class_data_student (2).csv to bertopic_class_data_student (2).csv
Uploaded file name: bertopic_class_data_student (2).csv

In [3]:
# Read the uploaded CSV file
import pandas as pd

df = pd.read_csv(filename)

print("Shape:", df.shape)
print("Columns:", list(df.columns))
df.head()

Shape: (258, 3)
Columns: ['text', 'clean_text', 'date']

,text,clean_text,date
0,The team delivered a steady floor routine duri...,team delivered steady floor routine all around...,2021-07-27
1,The all around final final featured a clean ba...,all around final final featured clean balance ...,2021-08-03
2,A strong performance in the freestyle race hel...,strong performance freestyle race helped secur...,2021-07-28
3,The vault event final featured a clean floor r...,vault event final featured clean floor routine...,2021-07-25
4,The track final at the track stadium ended wit...,track final track stadium ended thrilling heat...,2021-07-31

In [4]:
# Quick check to avoid common errors
required_cols = {"clean_text"}
missing_cols = required_cols - set(df.columns)

if missing_cols:
    raise ValueError(f"Missing required column(s): {missing_cols}")

print("Dataset is ready.")

Dataset is ready.

## Q1 (2 points) — Prepare the text data for topic modeling

Using the `clean_text` column, prepare a clean list of documents for BERTopic.

### Steps
- keep only non-null values from `clean_text`
- remove empty strings if there are any
- convert the result to a Python list called `docs`

### Then print
- the number of usable documents
- the first 3 documents

In [5]:
# Write your Answer here (Q1)
docs = df['clean_text'].dropna().loc[lambda s: s.str.strip() != ''].tolist()

print("Number of usable documents:", len(docs))
print("\nFirst 3 documents:")
for d in docs[:3]:
    print(d)

Number of usable documents: 258

First 3 documents:
team delivered steady floor routine all around final qualification round score arena
all around final final featured clean balance sequence strong result arena routine
strong performance freestyle race helped secure bronze medal team final record

## Q2 (3 points) — Train a BERTopic model

Use the cleaned `docs` list from Q1 and fit a BERTopic model.

### Steps
- create a BERTopic model with `language="english"`
- run `fit_transform(docs)`
- save the outputs in `topics` and `probs`

In [6]:
# Write your Answer here (Q2)
from bertopic import BERTopic

model = BERTopic(language="english")
topics, probs = model.fit_transform(docs)
print("Done. Topics assigned:", len(topics))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Done. Topics assigned: 258

## Q3 (2 points) — Topic summary

Display the output of `get_topic_info()`.

Then report:
1. the total number of **valid topics** discovered (**exclude `-1` if it appears**)
2. the ID of the **largest valid topic** (**exclude `-1`**)

**Hint:** you may want to filter `topic_info` first.

In [7]:
# Write your Answer here (Q3)
topic_info = model.get_topic_info()
display(topic_info)

valid_topics = topic_info[topic_info['Topic'] != -1]
print("Total valid topics:", len(valid_topics))
print("Largest valid topic ID:", valid_topics.loc[valid_topics['Count'].idxmax(), 'Topic'])

,Topic,Count,Name,Representation,Representative_Docs
0,0,40,0_vault_routine_balance_beam,"[vault, routine, balance, beam, event, all, ar...",[all around final qualification round featured...
1,1,40,1_medal_pool_freestyle_gold,"[medal, pool, freestyle, gold, butterfly, swim...",[swimming relay final pool exciting team won b...
2,2,40,2_ceremony_stadium_closing_opening,"[ceremony, stadium, closing, opening, celebrat...",[stadium looked amazing opening ceremony dance...
3,3,28,3_offense_team_important_last,"[offense, team, important, last, quarter, wome...",[strong teamwork last second half helped natio...
4,4,27,4_race_sprint_brought_runner,"[race, sprint, brought, runner, track, amazing...",[amazing fast finish m sprint brought bronze m...
5,5,26,5_court_baseline_shots_tennis,"[court, baseline, shots, tennis, dramatic, ser...",[singles final center court long baseline shot...
6,6,18,6_day_city_changed_issues,"[day, city, changed, issues, about, talked, qu...",[weather city changed quickly many people talk...
7,7,14,7_stayed_calm_player_set,"[stayed, calm, player, set, earned, place, pod...",[player stayed calm final set earned medal mat...
8,8,13,8_reacted_loudly_crowd_stadium,"[reacted, loudly, crowd, stadium, track, heat,...",[crowd reacted loudly relay race final track s...
9,9,12,9_coach_praised_men_defense,"[coach, praised, men, defense, team, group, se...",[coach praised men team group match arena defe...

Total valid topics: 10
Largest valid topic ID: 0

## Q4 (2 points) — Inspect one topic

Choose one valid topic ID (**not `-1`**) and print its **top 5 words**.

In [8]:
# Write your Answer here (Q4)
chosen_topic = valid_topics.loc[valid_topics['Count'].idxmax(), 'Topic']
print(f"Top 5 words for Topic {chosen_topic}:")
for word, score in model.get_topic(chosen_topic)[:5]:
    print(f"  {word}: {score:.4f}")

Top 5 words for Topic 0:
  vault: 0.1419
  routine: 0.1384
  balance: 0.1238
  beam: 0.1238
  event: 0.1119

## Q5 (1 point) — Assign topics back to the texts

Create a new DataFrame with these two columns:
- `clean_text`
- `topic`

Then print the first 5 rows.

In [9]:
# Write your Answer here (Q5)
docs_topics_df = pd.DataFrame({"clean_text": docs, "topic": topics})
docs_topics_df.head()

                                          clean_text  topic
0  team delivered steady floor routine all around...      0
1  all around final final featured clean balance ...      0
2  strong performance freestyle race helped secur...      1
3  vault event final featured clean floor routine...      0
4  track final track stadium ended thrilling heat...      4

## Grading Checklist

- **Q1 (2 pts):** documents prepared correctly from `clean_text`
- **Q2 (3 pts):** BERTopic model trained correctly on `docs`
- **Q3 (2 pts):** topic summary displayed and answers reported correctly
- **Q4 (2 pts):** one valid topic selected and top 5 words shown correctly
- **Q5 (1 pt):** topic assignment DataFrame created correctly